// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Chetas1/grpc-blog-service/internal/store (interfaces: BlogStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_store.go -package=mocks github.com/Chetas1/grpc-blog-service/internal/store BlogStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	proto "github.com/Chetas1/grpc-blog-service/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockBlogStore is a mock of BlogStore interface.
type MockBlogStore struct {
	ctrl     *gomock.Controller
	recorder *MockBlogStoreMockRecorder
	isgomock struct{}
}

// MockBlogStoreMockRecorder is the mock recorder for MockBlogStore.
type MockBlogStoreMockRecorder struct {
	mock *MockBlogStore
}

// NewMockBlogStore creates a new mock instance.
func NewMockBlogStore(ctrl *gomock.Controller) *MockBlogStore {
	mock := &MockBlogStore{ctrl: ctrl}
	mock.recorder = &MockBlogStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogStore) EXPECT() *MockBlogStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlogStore) Create(post *proto.Post) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", post)
}

// Create indicates an expected call of Create.
func (mr *MockBlogStoreMockRecorder) Create(post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlogStore)(nil).Create), post)
}

// Delete mocks base method.
func (m *MockBlogStore) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlogStoreMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlogStore)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockBlogStore) Get(id string) (*proto.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*proto.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBlogStoreMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBlogStore)(nil).Get), id)
}

// Update mocks base method.
func (m *MockBlogStore) Update(id, title, content, author string, tags []string) (*proto.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, title, content, author, tags)
	ret0, _ := ret[0].(*proto.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBlogStoreMockRecorder) Update(id, title, content, author, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBlogStore)(nil).Update), id, title, content, author, tags)
}
